BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[CropPrice] (
    [id] NVARCHAR(1000) NOT NULL,
    [crop] NVARCHAR(1000) NOT NULL,
    [region] NVARCHAR(1000) NOT NULL,
    [price] FLOAT(53) NOT NULL,
    [date] DATETIME2 NOT NULL CONSTRAINT [CropPrice_date_df] DEFAULT CURRENT_TIMESTAMP,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [CropPrice_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [CropPrice_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
